### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by rec3141** [fawaz-dabbaghieh/gfa_subgraphs#1]
Hi there, I'd love to use this program but it's not working for me, it just dies immediately after running with the following output in the log file

[2021-12-03 14:10:08,891] argument given: /home/rec3141/.local/bin/GFASubgraph -g CBL-1-46.gfa --log DEBUG output_comps --output_dir compos
[2021-12-03 14:10:08,892] Reading Graph...

**Comment by fawaz-dabbaghieh** [comment]
I just tested it on some GFAs I have and it worked, won't be able to diagnose the problem if I don't have the input file you're using.
Which GFA version are you using? GFASubgraph only works on GFA1.
If it's possible to send me your input file, I can try to diagnose the problem

**Comment by fawaz-dabbaghieh** [comment]
@rec3141 There's a new version now, maybe you can try that. I was still not able to reproduce the problem you had, I've tested on several GFA graphs and it worked for me. If the problem you are having still persists, please try to send me the graph you are working on, so I can debug the issue.

**Comment by fawaz-dabbaghieh** [comment]
I'm closing this issue for now as I haven't heard from you about whether this is fixed or not
