### ISSUE TITLE
feature wishlist - select components to extract by node ID

### ISSUE THREAD

**Issue by syueqiao** [fawaz-dabbaghieh/gfa_subgraphs#2]
hi! This has been a super useful tool for me, as I've been investigating the complexity of some GFAs from assemblies. 

I have some specific nodes of interest, and was wondering if it would be possible to provide a node ID to the output_comps command in order to extract only the component that contains my input node? Some of my graphs are very large, and I would like to be able to extract only a subset to reduce the resources needed. 

Thanks so much!

**Comment by fawaz-dabbaghieh** [comment]
Hi,

Thank you for your interest. Actually, your question came in at the right time, as I am working on making a GFA library that is more user-friendly and multipurpose so people can just import it to their project and manipulate the graph however they want.

Please also take a look at this other project I am working on ([extgfa](https://github.com/fawaz-dabbaghieh/extgfa)). Which also has a Graph class that can be imported and used. Also allows an external memory representation of GFAs. But if you GFAs are not extremely huge, you don't need to do the external memory stuff, you can just use the `Graph` class implemented there.
So feel free to add feature requests on the `extgfa` repository.

As for your specific questions, this can already be achieved with `GFASubgraph`  by using the `bfs` subcommand, you can then give the desired node as the start node, and for the neighborhood size, give some very large integer. The idea here is that it will perform BFS (Breadth First Search) starting from that node and will stop when it either hits that integer limit you gave or the all the nodes in the components are marked as visited, and returns that component. So just make sure the integer you give is larger than the component or larger the whole graph just to be safe.

Something like this:
```
GFASubgraph -g in_graph.gfa bfs --start node_id --neighborhood_size 20000000 --output_neighborhood output_component.gfa
```

**Comment by syueqiao** [comment]
hi Fawaz, that's great to hear, will definitely be checking out extgfa too as I have some very large GFAs as well :)

Thanks for the tips on using bfs, this is super helpful!

**Comment by fawaz-dabbaghieh** [comment]
@syueqiao you're welcome. Let me know if this worked for you so I can close the issue.
Freel free to open this or other issues when you need any help :)

**Comment by syueqiao** [comment]
yes it does, the issue can be closed! Thanks for taking the time to respond :)
